MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OOO00KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXkl:,,,,,,,,,:lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMN0o:,,,,,,,,,,,,,,,;o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMW0l,,,,,,,,,,,,,,,,,,,,,l0WMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXd,,,,,,,,,,,,,,,,,,,,,,,,,dXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNx,,,,,,,,,,,,,,,,,,,,,,,,,,,xNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMK:,,,,,,,,,,,,,,,,,,,,,,,,,,,:KMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM0:,,,;:::;,,,,,,,,,,,,,;:::;,,:0MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWO:;xXNNNX0d:,,,,,,,;d0XNNNXx;:OWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0kNMMMMMMMNx:,,,;xNMMMMMMMNk0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,,,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,,,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,,,dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWX0kxxk0XWNo,,,oNWX0kxxk0XWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMKl:,,,,,,:ldo,,,odl:,,,,,,:lKMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNo,,,,,,,,,,,,,,,,,,,,,,,,,,,oNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXl,,,,,,,,,,,,,,,,,,,,,,,,,,,lXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0c,,,,,,,,,,;:::;,,,,,,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXkc,,,,,,,,:ooo:,,,,,,,,ckXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWKko:,,,,,,,,,,,,,;okKWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNK0OkkkkkOO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMM                                                                  MMM
MMM  TTTTT  AAA  L      W   W  III  N   N  DDDD  EEEEE  RRRR         MMM
MMM    T   A   A L      W   W   I   NN  N  D   D E      R   R        MMM
MMM    T   AAAAA L      W W W   I   N N N  D   D EEEE   RRRR         MMM
MMM    T   A   A L      WW WW   I   N  NN  D   D E      R  R         MMM
MMM    T   A   A LLLLL  W   W  III  N   N  DDDD  EEEEE  R   R        MMM
MMM                                                                  MMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM